{% set name = "python-magnumclient" %}
{% set version = "3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 74818a5ae973299d77a682d3952f1299a1118fac4d33e3647af2c7f06892677e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - magnum = magnumclient.shell:main

requirements:
  host:
    - pbr !=2.1.0,>=2.0.0
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pbr !=2.1.0,>=2.0.0
    - babel >2.4.0
    - keystoneauth1 >=3.4.0
    - stevedore >=1.20.0
    - requests >=2.14.2
    - oslo.i18n >=3.15.3
    - oslo.log >=3.36.0
    - oslo.serialization >=2.19.2
    - oslo.utils >=3.33.0
    - os-client-config >=1.28.0
    - osc-lib >=1.8.0
    - prettytable >=0.7.2
    - cryptography >=3.0
    - decorator >=3.4.0

test:
  imports:
    - magnumclient

  commands:
    - magnum -h

about:
  home: https://docs.openstack.org/python-magnumclient/latest/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Client library for Openstack Magnum API
  dev_url: https://docs.openstack.org/infra/manual/developers.html

extra:
  recipe-maintainers:
    - tschoonj
